server:
  port: 8080
  servlet:
    context-path: /sso
spring:
  application:
    name: SSO
  datasource:
    username: root
    password: muyangren8
    url: jdbc:mysql://localhost:3306/chartView?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    database: 0
    host: 192.168.25.153
    port: 6379
    password:
    # 连接超时时间（ms)
    timeout: 5000
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 1
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.infinova.sso.entity


# jwt过期时间，单位分钟
jwt_expire_time: 60

