server:
  port: 8080
  servlet:
    context-path: /sso
spring:
  application:
    name: SSO
  datasource:
    username: smssend
    password: smssend
    url: jdbc:oracle:thin:@111.1.1.82:1521:spora
    driver-class-name: oracle.jdbc.OracleDriver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      default-transaction-isolation: 2
      max-wait-millis: 10000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.infinova.sso.entity


# jwt过期时间，单位分钟
jwt_expire_time: 1440

