server:
  port: 8081
  servlet:
    context-path: /cart
spring:
  datasource:
    username: smssend
    password: smssend
    url: jdbc:oracle:thin:@111.1.1.82:1521:spora
#    username: scott
#    password: muyangren8
#    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      default-transaction-isolation: 2
      max-wait-millis: 10000


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.qhj.cart.domain

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


#市场服务端ip
cartSeverHost: http://localhost:8080
